# Development environment configuration for multi-service application
# Services:
# - Frontend: React/Next.js application (port 3000)
# - Backend: Node.js/Express API (port 4000)
# - Database: PostgreSQL instance
# - Fluent-bit: Sidecar container for log aggregation
#
# Usage:
# - Development: docker-compose up
# - Testing: docker-compose up -d
# - Cleanup: docker-compose down -v

version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:4000
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: frontend.logs
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://db:5432/app
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: backend.logs
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=localdev
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fluent-bit:
    image: fluent/fluent-bit
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - "24224:24224"
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
