# Main CI/CD Pipeline
# This workflow handles the complete CI/CD process including:
# - Running tests
# - Security scanning (tfsec for Terraform, hadolint for Dockerfiles)
# - Building and pushing Docker images to ECR
# - Deploying infrastructure with Terraform
# - Deploying to ECS with zero downtime

name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1  # First reference
  PROJECT_NAME: microservice-app

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role  # Updated to match existing role
          aws-region: ${{ env.AWS_REGION }}  # Use environment variable instead of hardcoded value
          audience: sts.amazonaws.com
          role-duration-seconds: 900

      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity

      # Add your other deployment steps here
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: |
          cd terraform
          terraform init
